// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnysxIT6FpM-kJDex6S1BGcbS7DpVPGfk',
    appId: '1:562462742204:web:067e563e109beb9b5d22b9',
    messagingSenderId: '562462742204',
    projectId: 'sccourier-ed01b',
    authDomain: 'sccourier-ed01b.firebaseapp.com',
    storageBucket: 'sccourier-ed01b.firebasestorage.app',
    measurementId: 'G-HLCCPGDLCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZkuZKdqsEk15QgYOJYZ2oDrxyTkKAVE',
    appId: '1:562462742204:android:feca92e8faa82f725d22b9',
    messagingSenderId: '562462742204',
    projectId: 'sccourier-ed01b',
    storageBucket: 'sccourier-ed01b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5sS8hmhAoic7VFobw6ZtkXTI45eYi-g',
    appId: '1:562462742204:ios:3e649db147355c565d22b9',
    messagingSenderId: '562462742204',
    projectId: 'sccourier-ed01b',
    storageBucket: 'sccourier-ed01b.firebasestorage.app',
    iosClientId: '562462742204-da93bcsnpe0ifkkkvnk5su84nt4k97si.apps.googleusercontent.com',
    iosBundleId: 'com.example.scCourier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5sS8hmhAoic7VFobw6ZtkXTI45eYi-g',
    appId: '1:562462742204:ios:3e649db147355c565d22b9',
    messagingSenderId: '562462742204',
    projectId: 'sccourier-ed01b',
    storageBucket: 'sccourier-ed01b.firebasestorage.app',
    iosClientId: '562462742204-da93bcsnpe0ifkkkvnk5su84nt4k97si.apps.googleusercontent.com',
    iosBundleId: 'com.example.scCourier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnysxIT6FpM-kJDex6S1BGcbS7DpVPGfk',
    appId: '1:562462742204:web:7ead029de283c4055d22b9',
    messagingSenderId: '562462742204',
    projectId: 'sccourier-ed01b',
    authDomain: 'sccourier-ed01b.firebaseapp.com',
    storageBucket: 'sccourier-ed01b.firebasestorage.app',
    measurementId: 'G-LRMBTCQRJS',
  );
}
